apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mychart.name" . }}-production
  labels:
{{ include "mychart.labels" . | indent 4 }}
    app: {{ template "mychart.name" . }}
    version: v1
spec:
  replicas: {{ .Values.prodDeployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mychart.name" . }}
      app: {{ template "mychart.name" . }}
      version: v1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mychart.name" . }}
        app: {{ template "mychart.name" . }}
        version: v1
        canary: "{{ .Values.prodDeployment.flag }}"
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "mychart.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-canary
          image: "{{ .Values.prodDeployment.image.repository }}:{{ .Values.prodDeployment.image.tag }}"
          imagePullPolicy: {{ .Values.prodDeployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
