# Source: devops-assignment/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-assignment
  labels:
    account: devops-assignment
---
# Source: devops-assignment/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: devops-assignment
  labels:
    app: devops-assignment 
    service: devops-assignment
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: devops-assignment
---
# Source: devops-assignment/templates/deployment-canary.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-assignment-canary
  labels:
    app: devops-assignment
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-assignment
      version: v1
  template:
    metadata:
      labels:
        app: devops-assignment
        version: v1
        canary: "true"
    spec:
      serviceAccountName: devops-assignment
      containers:
        - name: devops-assignment
          image: "harsha0806/demo-app-v2:v1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
---
# Source: devops-assignment/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-assignment-production
  labels:
    app: devops-assignment
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-assignment
      version: v1
  template:
    metadata:
      labels:
        app: devops-assignment
        version: v1
        canary: "false"
    spec:
      serviceAccountName: devops-assignment
      containers:
        - name: devops-assignment-canary
          image: "harsha0806/demo-app-v1:v1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
---
# Source: devops-assignment/templates/istioDestinationRule.yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: devops-assignment-destination-rule
  labels:
    chart: devops-assignment-0.1.0
spec:
  host: devops-assignment
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: production
    labels:
      canary: "false"
  - name: canary
    labels:
      canary: "true"
---
# Source: devops-assignment/templates/istioGateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: devops-assignment-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
# Source: devops-assignment/templates/istioVirtualService.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: devops-assignment-virtual-service
  labels:
    chart: devops-assignment-0.1.0
spec:
  hosts:
  - "*"
  gateways:
  - devops-assignment-gateway
  http:
  - match:
    - uri:
        exact: /health
    - uri:
        prefix: /
    route:
    - destination:
        host: devops-assignment
        subset: production
        port:
          number: 8080
      weight: 100
    - destination:
        host: devops-assignment
        subset: canary
        port:
          number: 8080
      weight: 0
