apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ template "mychart.name" . }}-destination-rule
  labels:
    chart: {{ template "mychart.name" . }}-0.1.0
spec:
  host: {{ template "mychart.name" . }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: production
    labels:
      canary: "{{ .Values.prodDeployment.flag }}"
  - name: canary
    labels:
      canary: "{{ .Values.canaryDeployment.flag }}"
